language: objective-c
osx_image: xcode10.3
branches:
  only:
    - CI
    - master
before_install:
  - gem install fastlane --no-rdoc --no-ri
install: true
script:
  - fastlane scan -s SimpleAppUITests
